version: '3.8'

services:
  frontend:
    image: vue-shareblood:latest
    container_name: vue-shareblood-container
    ports:
      - "8080:80"
    restart: unless-stopped
    command: nginx -g "daemon off;"

